In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("empsal_part_buck.csv")

In [5]:
test = df.groupby("dept")

In [8]:
test.agg({"sal":"sum"})

                 sal
dept
Engineering  1415600
Finance      1303300
HR            970500
IT           1406100
Marketing    1089700
Sales         997500

In [11]:
test.agg({"sal":"max"})

               sal
dept
Engineering  91700
Finance      86700
HR           88500
IT           91300
Marketing    85400
Sales        91500

In [ ]:
sum,max,min,count,avg

In [12]:
test.agg({"sal":min})

C:\Users\AI NEXUT IT\AppData\Local\Temp\ipykernel_20724\74231572.py:1: FutureWarning: The provided callable <built-in function min> is currently using SeriesGroupBy.min. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "min" instead.
  test.agg({"sal":min})

               sal
dept
Engineering  61100
Finance      55900
HR           55300
IT           66800
Marketing    53200
Sales        54400

In [17]:
test.agg({"sal":"mean"})

                      sal
dept
Engineering  74505.263158
Finance      68594.736842
HR           64700.000000
IT           82711.764706
Marketing    68106.250000
Sales        71250.000000

In [ ]:
sum
min
max
len

In [18]:
test.agg({"sal":len})

             sal
dept
Engineering   19
Finance       19
HR            15
IT            17
Marketing     16
Sales         14

In [20]:
df['dept'].value_counts()

dept
Finance        19
Engineering    19
IT             17
Marketing      16
HR             15
Sales          14
Name: count, dtype: int64

In [22]:
df[df['city']=='New York'].groupby("dept").agg({"sal":"sum"})

  empid     empname      city    sal  age         dob     dept
0  E001  John Adams  New York  73400   29  1996-08-12  Finance

In [ ]:
#Assigment : 
dept -- max sal -- dept

In [ ]:
8. Time Series
pd.to_datetime() – Convert to datetime format.
df['date'].dt.year – Extract the year from a datetime column.
df['date'].dt.month – Extract the month from a datetime column.
df['date'].dt.day – Extract the day from a datetime column.
df['date'].dt.weekday – Extract the weekday.
df['date'].dt.isocalendar() – Get the ISO calendar year, week, and day.
df['date'].dt.month_name() – Get the name of the month.
df['date'].dt.strftime() – Convert a datetime to a string with a custom format.
df.resample() – Resample time series data.
df.shift() – Shift data by a specified number of periods.
df.diff() – Calculate the difference between consecutive data points.

In [ ]:
data type change --- 
1.astype -- int- str -- str int

2.to_datetime

In [24]:
df.dtypes

empid      object
empname    object
city       object
sal         int64
age         int64
dob        object
dept       object
dtype: object

In [33]:
df['sal'] = df['sal'].astype('int64')

In [34]:
df.dtypes

empid      object
empname    object
city       object
sal         int64
age         int64
dob        object
dept       object
dtype: object

In [36]:
df['new_date']= pd.to_datetime(df['dob'])

In [38]:
df.dtypes

empid               object
empname             object
city                object
sal                  int64
age                  int64
dob                 object
dept                object
new_date    datetime64[ns]
dtype: object

In [41]:
df['month'] = df['new_date'].dt.month

In [43]:
df['new_date'].dt.year

0     1996
1     1991
2     1984
3     1998
4     1980
      ...
95    2001
96    1993
97    1991
98    1995
99    1987
Name: new_date, Length: 100, dtype: int32

In [45]:
df['day']= df['new_date'].dt.day

In [47]:
df['year']= df['new_date'].dt.year

In [48]:
df

,empid,empname,city,sal,age,dob,dept,new_date,month,day,year
0,E001,John Adams,New York,73400,29,1996-08-12,Finance,1996-08-12,8,12,1996
1,E002,Sarah Miller,Los Angeles,81200,34,1991-04-23,HR,1991-04-23,4,23,1991
2,E003,Michael Brown,Chicago,65400,41,1984-02-11,Engineering,1984-02-11,2,11,1984
3,E004,Emily Davis,Houston,58900,27,1998-06-04,Marketing,1998-06-04,6,4,1998
4,E005,Daniel Wilson,Phoenix,91300,45,1980-09-19,IT,1980-09-19,9,19,1980
...,...,...,...,...,...,...,...,...,...,...,...
95,E096,Elise Hardy,Des Moines,58300,24,2001-05-30,HR,2001-05-30,5,30,2001
96,E097,Camden Bush,Modesto,72800,32,1993-04-03,Engineering,1993-04-03,4,3,1993
97,E098,Madeline Abbott,Fayetteville,75600,34,1991-01-28,Marketing,1991-01-28,1,28,1991
98,E099,Robert Drake,Shreveport,69100,30,1995-06-09,Finance,1995-06-09,6,9,1995
99,E100,Aurora Briggs,Akron,82300,38,1987-10-01,IT,1987-10-01,10,1,1987

In [ ]:
Datetime -- >
dd-mm-yyyy
dd-mm-yy
dd-Month-yyyy
Directives

%d-%m-%Y %y
%B %b

In [57]:
df['new_date'].dt.strftime('%Y-%b-%d %I:%H %p')

0     1996-Aug-12 12:00 AM
1     1991-Apr-23 12:00 AM
2     1984-Feb-11 12:00 AM
3     1998-Jun-04 12:00 AM
4     1980-Sep-19 12:00 AM
              ...
95    2001-May-30 12:00 AM
96    1993-Apr-03 12:00 AM
97    1991-Jan-28 12:00 AM
98    1995-Jun-09 12:00 AM
99    1987-Oct-01 12:00 AM
Name: new_date, Length: 100, dtype: object

In [ ]:
datetime -- https://docs.python.org/3/library/datetime.html

In [58]:
import datetime

In [67]:
filename = 'copper_daily_{}.csv'
filename.format(datetime.datetime.now())

'copper_daily_2026-07-21 21:36:30.810520.csv'

In [68]:
df['todays'] = datetime.datetime.now()

In [71]:
df['todays'].dt.strftime('%d-%m-%Y %H:%H %p')

0     21-07-2026 21:21 PM
1     21-07-2026 21:21 PM
2     21-07-2026 21:21 PM
3     21-07-2026 21:21 PM
4     21-07-2026 21:21 PM
             ...
95    21-07-2026 21:21 PM
96    21-07-2026 21:21 PM
97    21-07-2026 21:21 PM
98    21-07-2026 21:21 PM
99    21-07-2026 21:21 PM
Name: todays, Length: 100, dtype: object

In [ ]:
Doj -- Exp

Dob -- age

yest --  tr -- diff --  -- min -- H - M --  total sec

time delta --

In [74]:
df['todays'].dt.tz_localize("UTC")

0    2026-07-21 21:36:31.343051+00:00
1    2026-07-21 21:36:31.343051+00:00
2    2026-07-21 21:36:31.343051+00:00
3    2026-07-21 21:36:31.343051+00:00
4    2026-07-21 21:36:31.343051+00:00
                   ...
95   2026-07-21 21:36:31.343051+00:00
96   2026-07-21 21:36:31.343051+00:00
97   2026-07-21 21:36:31.343051+00:00
98   2026-07-21 21:36:31.343051+00:00
99   2026-07-21 21:36:31.343051+00:00
Name: todays, Length: 100, dtype: datetime64[us, UTC]

In [98]:
from datetime import datetime
from zoneinfo import ZoneInfo

# A naive datetime (no timezone attached)
naive_dt = datetime.now()

# Attach a specific time zone to make it "aware"
london_dt = naive_dt.replace(tzinfo=ZoneInfo("Europe/London"))
london_dt

datetime.datetime(2026, 7, 21, 21, 51, 51, 999830, tzinfo=zoneinfo.ZoneInfo(key='Europe/London'))

In [99]:
df['temp'] = naive_dt

In [86]:
df['london_date_time']=london_dt

In [101]:
df['temp'].dt.tz_localize('Asia/Singapore')

0    2026-07-21 21:51:51.999830+08:00
1    2026-07-21 21:51:51.999830+08:00
2    2026-07-21 21:51:51.999830+08:00
3    2026-07-21 21:51:51.999830+08:00
4    2026-07-21 21:51:51.999830+08:00
                   ...
95   2026-07-21 21:51:51.999830+08:00
96   2026-07-21 21:51:51.999830+08:00
97   2026-07-21 21:51:51.999830+08:00
98   2026-07-21 21:51:51.999830+08:00
99   2026-07-21 21:51:51.999830+08:00
Name: temp, Length: 100, dtype: datetime64[us, Asia/Singapore]

In [ ]:
pd.to_datetime() – Convert to datetime format.
df['date'].dt.year – Extract the year from a datetime column.
df['date'].dt.month – Extract the month from a datetime column.
df['date'].dt.day – Extract the day from a datetime column.
df['date'].dt.weekday – Extract the weekday.
df['date'].dt.isocalendar() – Get the ISO calendar year, week, and day.
df['date'].dt.month_name() – Get the name of the month.
df['date'].dt.strftime() – Convert a datetime to a string with a custom format.
df.resample() – Resample time series data.
df.shift() – Shift data by a specified number of periods.
df.diff() – Calculate the difference between consecutive data points.

In [104]:
df['new_date'].dt.month_name()

0        August
1         April
2      February
3          June
4     September
        ...
95          May
96        April
97      January
98         June
99      October
Name: new_date, Length: 100, dtype: object

In [ ]:
datetime

In [ ]:
data  -- file -- read 


file write

In [107]:
df.to_csv("test1.csv",index=False)

In [109]:
df.to_html("temp.html")

In [ ]:
arquet -- most -- -binary data ---

In [ ]:
.parquet

In [ ]:
transform 
rank
dense_rank
row_number
lead
lag
=======================