In [1]:
import pandas as pd

In [40]:
df = pd.read_csv("empsal_part_buck.csv")

In [3]:
df

   empid          empname          city    sal  age         dob         dept
0   E001       John Adams      New York  73400   29  1996-08-12      Finance
1   E002     Sarah Miller   Los Angeles  81200   34  1991-04-23           HR
2   E003    Michael Brown       Chicago  65400   41  1984-02-11  Engineering
3   E004      Emily Davis       Houston  58900   27  1998-06-04    Marketing
4   E005    Daniel Wilson       Phoenix  91300   45  1980-09-19           IT
..   ...              ...           ...    ...  ...         ...          ...
95  E096      Elise Hardy    Des Moines  58300   24  2001-05-30           HR
96  E097      Camden Bush       Modesto  72800   32  1993-04-03  Engineering
97  E098  Madeline Abbott  Fayetteville  75600   34  1991-01-28    Marketing
98  E099     Robert Drake    Shreveport  69100   30  1995-06-09      Finance
99  E100    Aurora Briggs         Akron  82300   38  1987-10-01           IT

[100 rows x 7 columns]

In [4]:
df['rank']= df['sal'].rank()

In [7]:
df['sal'].min()

53200

In [9]:
df[df['sal']==53200]

   empid        empname       city    sal  age         dob       dept  rank
53  E054  Sadie Ramirez  Santa Ana  53200   23  2002-10-06  Marketing   1.0

In [11]:
df[df['rank']==1.0]

   empid        empname       city    sal  age         dob       dept  rank
53  E054  Sadie Ramirez  Santa Ana  53200   23  2002-10-06  Marketing   1.0

In [12]:
df['rank']= df['sal'].rank(ascending=False)

In [15]:
df[df['sal']==df['sal'].max()]

,empid,empname,city,sal,age,dob,dept,rank
73,E074,Brooklyn Bryant,Henderson,91700,41,1984-03-29,Engineering,1.0

In [18]:
df[df['rank']==3.0]

  empid        empname     city    sal  age         dob dept  rank
4  E005  Daniel Wilson  Phoenix  91300   45  1980-09-19   IT   3.0

In [ ]:
Interview :

rank |dense rank -- deptwise

In [19]:
df['rank_by_dept']= df.groupby('dept')['sal'].rank(ascending=False)

In [22]:

df[df['rank_by_dept']==1.0]

,empid,empname,city,sal,age,dob,dept,rank,rank_by_dept
4,E005,Daniel Wilson,Phoenix,91300,45,1980-09-19,IT,3.0,1.0
31,E032,Riley Evans,Albuquerque,88500,41,1984-08-02,HR,11.0,1.0
41,E042,Victoria Bell,Virginia Beach,86700,40,1985-04-06,Finance,13.0,1.0
52,E053,Wyatt Gray,Honolulu,91500,45,1980-05-20,Sales,2.0,1.0
65,E066,Elena Coleman,Orlando,85400,37,1988-07-13,Marketing,16.0,1.0
73,E074,Brooklyn Bryant,Henderson,91700,41,1984-03-29,Engineering,1.0,1.0

In [23]:
df =pd.DataFrame({"id":[1,2,3,4,5],
                  "name":['a','b','c','d','e'],
                  "sal":[10,20,20,20,30]
                 })

In [31]:
df['rank'] = df['sal'].rank(method='max')

In [33]:
df['dense'] = df['sal'].rank(method='dense')

In [ ]:
min
max
avg

In [ ]:
Domain -- DE -- Domain -- SME -- BA  -- Stack Holder

In [34]:
df

   id name  sal  rank  dense
0   1    a   10   1.0    1.0
1   2    b   20   4.0    2.0
2   3    c   20   4.0    2.0
3   4    d   20   4.0    2.0
4   5    e   30   5.0    3.0

In [38]:
df['rn'] = df.index+1

In [39]:
df

   id name  sal  rank  dense  rn
0   1    a   10   1.0    1.0   1
1   2    b   20   4.0    2.0   2
2   3    c   20   4.0    2.0   3
3   4    d   20   4.0    2.0   4
4   5    e   30   5.0    3.0   5

In [42]:
df['rn']= df.groupby("dept").cumcount()+1

In [47]:
df[df['dept']=='IT']

   empid           empname              city    sal  age         dob dept  rn
4   E005     Daniel Wilson           Phoenix  91300   45  1980-09-19   IT   1
9   E010     Olivia Martin          San Jose  66800   33  1992-07-30   IT   2
14  E015         Noah King         Charlotte  90400   42  1983-06-19   IT   3
21  E022     Lily Gonzalez           El Paso  69200   31  1994-04-27   IT   4
27  E028     Hannah Turner         Las Vegas  84700   35  1990-11-25   IT   5
33  E034  Penelope Collins            Fresno  91200   38  1987-12-09   IT   6
38  E039       Joseph Reed  Colorado Springs  70700   28  1997-02-19   IT   7
44  E045    Anthony Rivera             Tulsa  90200   42  1983-07-15   IT   8
50  E051        Leo Torres           Anaheim  80400   36  1989-04-17   IT   9
56  E057    Grayson Brooks            Irvine  85700   38  1987-02-28   IT  10
62  E063   Jonathan Barnes         Anchorage  87700   39  1986-06-22   IT  11
68  E069    Charles Powell       Chula Vista  83200   35  1990-05-25   IT  12
76  E077      Nolan Graham           Buffalo  72400   32  1993-02-02   IT  13
82  E083  Christian Warren           Garland  86100   40  1985-03-05   IT  14
88  E089    Gabriel Bryant   North Las Vegas  90400   42  1983-11-06   IT  15
94  E095  Jordan Stevenson          Richmond  83400   37  1988-02-14   IT  16
99  E100     Aurora Briggs             Akron  82300   38  1987-10-01   IT  17

In [48]:
df

,empid,empname,city,sal,age,dob,dept,rn
0,E001,John Adams,New York,73400,29,1996-08-12,Finance,1
1,E002,Sarah Miller,Los Angeles,81200,34,1991-04-23,HR,1
2,E003,Michael Brown,Chicago,65400,41,1984-02-11,Engineering,1
3,E004,Emily Davis,Houston,58900,27,1998-06-04,Marketing,1
4,E005,Daniel Wilson,Phoenix,91300,45,1980-09-19,IT,1
...,...,...,...,...,...,...,...,...
95,E096,Elise Hardy,Des Moines,58300,24,2001-05-30,HR,15
96,E097,Camden Bush,Modesto,72800,32,1993-04-03,Engineering,19
97,E098,Madeline Abbott,Fayetteville,75600,34,1991-01-28,Marketing,16
98,E099,Robert Drake,Shreveport,69100,30,1995-06-09,Finance,19
99,E100,Aurora Briggs,Akron,82300,38,1987-10-01,IT,17

In [57]:
df['lead'] = df['sal'].shift(-5)

In [58]:
df.columns

Index(['empid', 'empname', 'city', 'sal', 'age', 'dob', 'dept', 'rn', 'lead'], dtype='object')

In [63]:
temp = df[['empid', 'empname',  'dept', 'rn', 'sal']]

In [60]:
df['lag'] = df['sal'].shift(1)

In [61]:
df

,empid,empname,city,sal,age,dob,dept,rn,lead,lag
0,E001,John Adams,New York,73400,29,1996-08-12,Finance,1,70200.0,NaN
1,E002,Sarah Miller,Los Angeles,81200,34,1991-04-23,HR,1,62300.0,73400.0
2,E003,Michael Brown,Chicago,65400,41,1984-02-11,Engineering,1,84500.0,81200.0
3,E004,Emily Davis,Houston,58900,27,1998-06-04,Marketing,1,57700.0,65400.0
4,E005,Daniel Wilson,Phoenix,91300,45,1980-09-19,IT,1,66800.0,58900.0
...,...,...,...,...,...,...,...,...,...,...
95,E096,Elise Hardy,Des Moines,58300,24,2001-05-30,HR,15,NaN,83400.0
96,E097,Camden Bush,Modesto,72800,32,1993-04-03,Engineering,19,NaN,58300.0
97,E098,Madeline Abbott,Fayetteville,75600,34,1991-01-28,Marketing,16,NaN,72800.0
98,E099,Robert Drake,Shreveport,69100,30,1995-06-09,Finance,19,NaN,75600.0
99,E100,Aurora Briggs,Akron,82300,38,1987-10-01,IT,17,NaN,69100.0

In [ ]:
rn | rank | dense |rank | lead | lag

In [62]:
df

,empid,empname,city,sal,age,dob,dept,rn,lead,lag
0,E001,John Adams,New York,73400,29,1996-08-12,Finance,1,70200.0,NaN
1,E002,Sarah Miller,Los Angeles,81200,34,1991-04-23,HR,1,62300.0,73400.0
2,E003,Michael Brown,Chicago,65400,41,1984-02-11,Engineering,1,84500.0,81200.0
3,E004,Emily Davis,Houston,58900,27,1998-06-04,Marketing,1,57700.0,65400.0
4,E005,Daniel Wilson,Phoenix,91300,45,1980-09-19,IT,1,66800.0,58900.0
...,...,...,...,...,...,...,...,...,...,...
95,E096,Elise Hardy,Des Moines,58300,24,2001-05-30,HR,15,NaN,83400.0
96,E097,Camden Bush,Modesto,72800,32,1993-04-03,Engineering,19,NaN,58300.0
97,E098,Madeline Abbott,Fayetteville,75600,34,1991-01-28,Marketing,16,NaN,72800.0
98,E099,Robert Drake,Shreveport,69100,30,1995-06-09,Finance,19,NaN,75600.0
99,E100,Aurora Briggs,Akron,82300,38,1987-10-01,IT,17,NaN,69100.0

In [69]:
temp['roll_3_mean'] = temp['sal'].rolling(window=3).mean()

C:\Users\AI NEXUT IT\AppData\Local\Temp\ipykernel_21292\376756688.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  temp['roll_3_mean'] = temp['sal'].rolling(window=3).mean()

In [70]:
temp

   empid          empname         dept  rn    sal  roll_3_max   roll_3_mean
0   E001       John Adams      Finance   1  73400         NaN           NaN
1   E002     Sarah Miller           HR   1  81200         NaN           NaN
2   E003    Michael Brown  Engineering   1  65400     81200.0  73333.333333
3   E004      Emily Davis    Marketing   1  58900     81200.0  68500.000000
4   E005    Daniel Wilson           IT   1  91300     91300.0  71866.666667
..   ...              ...          ...  ..    ...         ...           ...
95  E096      Elise Hardy           HR  15  58300     83400.0  68833.333333
96  E097      Camden Bush  Engineering  19  72800     83400.0  71500.000000
97  E098  Madeline Abbott    Marketing  16  75600     75600.0  68900.000000
98  E099     Robert Drake      Finance  19  69100     75600.0  72500.000000
99  E100    Aurora Briggs           IT  17  82300     82300.0  75666.666667

[100 rows x 7 columns]

In [ ]:
rolling --- windows -- trends -- visualize -- > prediction -->
avg -- moving -->

In [71]:
df =  pd.read_csv("emppivote.csv")

In [72]:
df

   product  month  sales
0   copper    Jan     56
1   copper    Feb     65
2   copper  March    324
3   copper  April     76
4   silver    Jan     67
5   silver    Feb     98
6   silver  March    345
7   silver  April     87
8     gold    Jan     45
9     gold    Feb     87
10    gold  March     45
11    gold  April     76

In [74]:
temp = df.pivot(index="product",columns="month",values="sales")

In [81]:
temp.loc[["copper","silver"],]

month    April  Feb  Jan  March
product
copper      76   65   56    324
silver      87   98   67    345

In [77]:
temp

month    April  Feb  Jan  March
product
copper      76   65   56    324
gold        76   87   45     45
silver      87   98   67    345

In [94]:
temp.melt(id_vars="product",value_vars="sales",)

KeyError: "The following id_vars or value_vars are not present in the DataFrame: ['product', 'sales']"

In [99]:
# multiple unpivot columns
temp.melt(id_vars=['product'], value_vars='sales')

KeyError: "The following id_vars or value_vars are not present in the DataFrame: ['product', 'sales']"

In [107]:
temp.melt(value_name="sales",id_vars="product")

KeyError: "The following id_vars or value_vars are not present in the DataFrame: ['product']"

In [108]:
melt

NameError: name 'melt' is not defined

In [112]:
pd.melt(temp,
    id_vars="product",
    var_name="month",
    value_name="sales"
)

KeyError: "The following id_vars or value_vars are not present in the DataFrame: ['product']"

In [111]:
temp

month    April  Feb  Jan  March
product
copper      76   65   56    324
gold        76   87   45     45
silver      87   98   67    345

In [113]:
import pandas as pd

# Pivoted DataFrame
df = pd.DataFrame({
    "product": ["copper", "gold", "silver"],
    "April": [76, 76, 87],
    "Feb": [65, 87, 98],
    "Jan": [56, 45, 67],
    "March": [324, 45, 345]
})

# Unpivot (melt)
unpivoted = df.melt(
    id_vars="product",
    var_name="month",
    value_name="sales"
)

print(unpivoted)

   product  month  sales
0   copper  April     76
1     gold  April     76
2   silver  April     87
3   copper    Feb     65
4     gold    Feb     87
5   silver    Feb     98
6   copper    Jan     56
7     gold    Jan     45
8   silver    Jan     67
9   copper  March    324
10    gold  March     45
11  silver  March    345

In [114]:
df

  product  April  Feb  Jan  March
0  copper     76   65   56    324
1    gold     76   87   45     45
2  silver     87   98   67    345

In [116]:
temp.reset_index(inplace=True)

In [118]:
temp.melt(
    id_vars="product",
    var_name="month",
    value_name="sales"
)

   product  month  sales
0   copper  April     76
1     gold  April     76
2   silver  April     87
3   copper    Feb     65
4     gold    Feb     87
5   silver    Feb     98
6   copper    Jan     56
7     gold    Jan     45
8   silver    Jan     67
9   copper  March    324
10    gold  March     45
11  silver  March    345

In [ ]:
pivote_table